### ISSUE TITLE
Send Server Image URL

### ISSUE THREAD

**Issue by asafros7** [Aramis13/green-specs#17]

**Comment by nitayk** [comment]
@Aramis13 
Server URL:  http://3.93.212.180/analyze (supports both GET and POST)
GET example: http://3.93.212.180/analyze?pic_url=https://r-cf.bstatic.com/images/hotel/max1024x768/213/213503505.jpg&id=123
POST example
body: {
id: 123,
pic_url: https://r-cf.bstatic.com/images/hotel/max1024x768/213/213503505.jpg
}

The response is currently a parsed SVG using svg-parser https://www.npmjs.com/package/svg-parser

This is what I am getting from dandan at the moment, later we can add Type and w/e
