### ISSUE TITLE
detailed plant index by ABC

### ISSUE THREAD

**Issue by asafros7** [Aramis13/green-specs#24]

**Comment by asafros7** [comment]
@Aramis13

**Comment by Aramis13** [comment]
Nice.

@nitayk We need to get a DB up and upload this data.

**Comment by asafros7** [comment]
https://docs.google.com/spreadsheets/d/1Tdpzuctx6aHP26JL0B9BeB3YE5tsHhhOaSLQP3wvjiM/edit?usp=sharing
