### ISSUE TITLE
Send lake polygon array (svg) + type + plants details

### ISSUE THREAD

**Issue by asafros7** [Aramis13/green-specs#7]
@Aramis13 the route is going to be /analyze?pic_url=<PIC_URL>&id-<SOME_UNIQUE_ID> / or post body
The reason for the unique ID is to be able to save the picture with a context.

Example:
http://localhost:8005/analyze
Post body:
id & pic_url

We still need to talk about the format (I have it as jpg hardcoded currently)

**Comment by Aramis13** [comment]
@nitayk I thought to use a _post_ method, you can just define the parameters that needed in the request body (like URL, userName etc.).
Also because were distributed i still need a full API URL (my-service.com/api/analyze) wherever you decide to run it.
