### ISSUE TITLE
Draw Zones On Top Original Image

### ISSUE THREAD

**Issue by asafros7** [Aramis13/green-specs#8]

**Comment by Aramis13** [comment]
@nitayk @danielgilon I will need to get a list of objects, Each object will contain:

- path: "m539,588.4c0,0 53,-1 53,-1c0,0 32,32 32,31.6c0,0.4 -16,37.4 -16,37c0,0.4 -36,5.4 -36,5.4c0,0 -42,-8 -44,-8c-2,0 -18,-24 -20,-24c-2,0 10,-38 10,-38.4c0,0.4 21,-2.6 21,-2.6z"

- type: "Low"

path is an _svg_ d value, example above. [https://www.w3schools.com/graphics/svg_path.asp](url)
type Low, Medium or High, illumination categories, example above.

#7 #16

**Comment by nitayk** [comment]
[https://www.w3schools.com/graphics/svg_path.asp](url)
